_target_: clip_policy.models.VINN
_partial_: true
encoder:
  _target_: clip_policy.models.ImageEncoder
  encoder_type: resnet18
  pretrained: True #False
enc_weight_pth: /home/robot-lab/hello-robot/anant/clip-policy/weights/byol_nlu_135.pth