_target_: models.nn.VINN
_partial_: true
encoder:
  _target_: models.encoders.encoder.ImageEncoder
  encoder_type: resnet18
  pretrained: True #False

# enc_weight_pth: None
# enc_weight_pth: /scratch/ar7420/VINN/imitation-in-homes/outputs/2023-04-22/02-57-10/weights/byol_chain_cabinet_test_105.pth